autolabeler:  # cspell:ignore autolabeler
  - label: bug
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: changelog:skip
  - label: documentation
    branch: [/^(docs)\/.*/]
  - label: feature
    branch: [/^(feat|feature)\/.*/]
  - label: maintenance
    branch: [/^(chore|maint|maintain|maintenance)\/.*/]
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'chore'
  - title: '📝 Document'
    labels:
      - 'documentation'

category-template: '## $TITLE'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
sort-by: 'title'

name-template: '$RESOLVED_VERSION'
template: |
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip_changelog'