name: On pr target

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
          disable-autolabeler: false
