name: On release

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Append CHANGELOG.md
        run: |
          echo -e "${{ github.event.release.body }}\n$(cat CHANGELOG.md)" > CHANGELOG.md
          echo -e "# ${{ github.event.release.name }}\n$(cat CHANGELOG.md)" > CHANGELOG.md
      - name: Commit and create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update CHANGELOG.md for release ${{ github.event.release.tag_name }}
          branch: chore/update-CHANGELOG-for-release-${{ github.event.release.tag_name }}
          base: main
          title: 'Update CHANGELOG for release ${{ github.event.release.tag_name }}'